wandb_version: 1

architecture:
  desc: null
  value: NGCF
batch_size:
  desc: null
  value: 16
layers:
  desc: null
  value:
  - 64
  - 32
emb_dim:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.01
reg:
  desc: null
  value: 0.01
mess_dropout:
  desc: null
  value: 0.1
node_dropout:
  desc: null
  value: 0.1
k:
  desc: null
  value: 10
epochs:
  desc: null
  value: 20
user_count:
  desc: null
  value: 1000
book_count:
  desc: null
  value: 488
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717776095
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
