wandb_version: 1

architecture:
  desc: null
  value: NGCF
loss:
  desc: null
  value: bpr
tr:
  desc: null
  value: 'True'
pcutoff:
  desc: null
  value: '0.9'
batch_size:
  desc: null
  value: 16
layers:
  desc: null
  value:
  - 16
  - 32
emb_dim:
  desc: null
  value: 52
lr:
  desc: null
  value: 0.015
reg:
  desc: null
  value: 0.005
mess_dropout:
  desc: null
  value: 0.01
node_dropout:
  desc: null
  value: 0.01
user_count:
  desc: null
  value: 36199
book_count:
  desc: null
  value: 5422
k:
  desc: null
  value: 20
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717955970
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.17.1
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
